import{a as L,S as g,i}from"./assets/vendor-mdVVRe9K.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&t(d)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const E="45185158-717bb7f7583789050cac5d72f",w="https://pixabay.com/api/",v=15;async function I(r,o=1){const n=`${w}?key=${E}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${v}&page=${o}`;try{return(await L.get(n)).data}catch(t){throw console.error("Error fetching data:",t),t}}let u=null;function $(r,o){const n=r.map(t=>`
    <a href="${t.largeImageURL}" class="gallery-item">
      <img src="${t.webformatURL}" alt="${t.tags}" />
      <div class="info">
        <p><b>Likes:</b> ${t.likes}</p>
        <p><b>Views:</b> ${t.views}</p>
        <p><b>Comments:</b> ${t.comments}</p>
        <p><b>Downloads:</b> ${t.downloads}</p>
      </div>
    </a>
  `).join("");o.insertAdjacentHTML("beforeend",n),u?u.refresh():u=new g(".gallery-item")}const R=document.getElementById("search-form"),a=document.getElementById("gallery"),l=document.querySelector(".btn"),y=document.getElementById("loader");let f="",c=1,m=0,h=0,P=new g(".gallery a");R.addEventListener("submit",function(r){if(r.preventDefault(),f=document.getElementById("search-input").value.trim(),c=1,m=0,h=0,!f){i.error({title:"Error",message:"Please enter a search term!"});return}a.innerHTML="",l.classList.add("hidden"),b()});l.addEventListener("click",function(){c+=1,b()});async function b(){B();try{const r=await I(f,c);p();const o=r.hits;if(m=r.totalHits,o.length===0&&c===1){i.error({title:"Info",message:"Sorry, no images match your search. Try again!",position:"topRight"});return}$(o,a),P.refresh(),h+=o.length,h>=m?(l.classList.add("hidden"),i.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):l.classList.remove("hidden"),S()}catch(r){p(),i.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error("Error:",r)}}function B(){y.classList.remove("hidden")}function p(){y.classList.add("hidden")}function S(){if(a.firstElementChild){const{height:r}=a.firstElementChild.getBoundingClientRect();setTimeout(()=>{window.scrollBy({top:r*4,behavior:"smooth"})},200)}}
//# sourceMappingURL=index.js.map
